yarnPath: .yarn/releases/yarn-sources.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

packageExtensions:
  react-dnd@*:
    dependencies:
      "@react-dnd/invariant": 2.0.0
